spring.application.name=employee
server.port = 9191
server.servlet.context-path = /invex
spring.datasource.url = jdbc:mysql://localhost:3306/invex
spring.datasource.username = invex
spring.datasource.password = P@@ssw00rd_2k26
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate-dll-auto = update
spring.jpa.show-sql = true
# ============================================================
# LOGGING CONFIGURATION
# ============================================================
# Nivel general de la aplicacion
logging.level.root=INFO
# Nivel especifico del paquete del proyecto
logging.level.invex.employee=DEBUG
# Nivel de Spring Web (requests/responses)
logging.level.org.springframework.web=INFO
# Nivel de Hibernate / SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Formato del log en consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Archivo de log
logging.file.name=logs/employee-api.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n